version: '3.4'

services:
  backend:
    image: ${DOCKER_REGISTRY-}backend
    ports:
      - "62612:80"
    build:
      context: .
      dockerfile: Backend/Dockerfile
  db:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "62613:80"
    environment:
      SA_PASSWORD: "Icocelic2808!"
      ACCEPT_EULA: "Y"
  vue-ui:
    build:
      context: ./../FrontZadatak/frontzadatak
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: vue-ui
    volumes:
       - ./../FrontZadatak/frontzadatak:/usr/src/app/frontzadatak
     