version: '3.4'

services:
  backend:
    image: ${DOCKER_REGISTRY-}backend
    ports:
      - "62612:80"
    build:
      context: .
      dockerfile: Backend/Dockerfile
  db:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "62613:80"
    environment:
      SA_PASSWORD: "Icocelic2808!"
      ACCEPT_EULA: "Y"